github:
patreon: 'user?u=95097899'
open_collective: 
ko_fi: 
tidelift: 
community_bridge: 
liberapay: 
issuehunt:
otechie: 
custom: ['https://captchas.io','https://freecaptchabypass.com','https://captchacoins.com','http://captchaproxies.com']
