github:
patreon:
open_collective: 
ko_fi: 
tidelift: 
community_bridge: 
liberapay: 
issuehunt:
otechie: 
custom: ['https://captchas.io','https://freearticles.io','https://submit.ph','http://captchaproxies.com', 'https://artikuls.com']
